# TODO: Remove assumption version is increased to unreleased version.

name: Publish
on: push
jobs:
  version:
    # Check if core or cli versions changed and output metadata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      # Check if core changed
      - name: Check @iota-wiki/core changed in current branch
        id: core-to-current
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: ./package.json
      - name: Check @iota-wiki/core changed compared to main branch
        if: github.ref != 'refs/heads/main'
        id: core-to-main
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: ./package.json
          file-url: https://raw.githubusercontent.com/iota-wiki/iota-wiki/main/package.json
          static-checking: localIsNew
      # Check if cli changed
      - name: Check @iota-wiki/cli changed in current branch
        id: cli-to-current
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: ./cli/package.json
      - name: Check @iota-wiki/cli changed compared to main branch
        if: github.ref != 'refs/heads/main'
        id: cli-to-main
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          file-name: ./cli/package.json
          file-url: https://raw.githubusercontent.com/iota-wiki/iota-wiki/main/cli/package.json
          static-checking: localIsNew
    outputs:
      core-changed: ${{ steps.core-to-current.outputs.changed == 'true' && (github.ref == 'refs/heads/main' || steps.core-to-main.outputs.changed == 'true') }}
      core-version: ${{ steps.core-to-current.outputs.version }}
      cli-changed: ${{ steps.cli-to-current.outputs.changed == 'true' && (github.ref == 'refs/heads/main' || steps.cli-to-main.outputs.changed == 'true') }}
      cli-version: ${{ steps.cli-to-current.outputs.version }}
  publish-core:
    # If not on main and version changed, publish with experimental tag
    runs-on: ubuntu-latest
    needs: version
    if: github.ref != 'refs/heads/main' && needs.version.outputs.core-changed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn install
      # Publish to NMP
      - name: Publish to NPM
        run: |
          yarn npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Publish to GitHub
      - name: Publish to GitHub
        run: |
          yarn npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
  publish-cli:
    # If not on main and version changed, publish with experimental tag
    runs-on: ubuntu-latest
    needs: version
    if: github.ref != 'refs/heads/main' && needs.version.outputs.cli-changed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Allow modern Yarn
        run: |
          corepack enable
      - name: Install dependencies
        run: |
          yarn install
      # Publish to NMP
      - name: Publish to NPM
        run: |
          yarn workspace @iota-wiki/cli npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Publish to GitHub
      - name: Publish to GitHub
        run: |
          yarn workspace @iota-wiki/cli npm publish --access public --tag experimental
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
  tag-core:
    # If on main and version changed, change tag to latest
    runs-on: ubuntu-latest
    needs: version
    if: github.ref == 'refs/heads/main' && needs.version.outputs.core-changed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Allow modern Yarn
        run: |
          corepack enable
      # Tag on NMP
      - name: Publish to NPM
        run: |
          yarn npm tag add @iota-wiki/core@${{ needs.version.outputs.core-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Tag on GitHub
      - name: Publish to GitHub
        run: |
          yarn npm tag add @iota-wiki/core@${{ needs.version.outputs.core-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
  tag-cli:
    # If on main and version changed, change tag to latest
    runs-on: ubuntu-latest
    needs: version
    if: github.ref == 'refs/heads/main' && needs.version.outputs.cli-changed
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Allow modern Yarn
        run: |
          corepack enable
      # Tag on NMP
      - name: Publish to NPM
        run: |
          yarn npm tag add @iota-wiki/cli@${{ needs.version.outputs.cli-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://registry.npmjs.org'
      # Tag on GitHub
      - name: Publish to GitHub
        run: |
          yarn npm tag add @iota-wiki/cli@${{ needs.version.outputs.cli-version }} latest
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: 'https://npm.pkg.github.com'
